In [1]:
import tensorflow as tf

C:\Users\HP\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epochs_end(self,epochs,logs={}):
        if(logs.get('acc')>0.99):
            print("\n Reached 99% accuracy so cancelling training")
            self.model.stop_training=True

In [3]:
mnist=tf.keras.datasets.mnist

In [4]:
sess=tf.Session()

In [5]:
mnist

<module 'tensorflow.keras.datasets.mnist' from 'C:\\Users\\HP\\Anaconda3\\lib\\site-packages\\tensorflow\\keras\\datasets\\mnist\\__init__.py'>

In [6]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [7]:
print(x_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [8]:
x_train,x_test=x_train/255.0,x_test/255.0

In [9]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [10]:
callback=myCallback()

In [11]:
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                  tf.keras.layers.Dense(512,activation=tf.nn.relu),
                                 tf.keras.layers.Dense(10,activation=tf.nn.softmax)])

In [12]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [13]:
model.fit(x_train,y_train,epochs=10,callbacks=[callback])

Epoch 1/10
60000/60000 [==============================] - 17s 284us/step - loss: 0.2009 - acc: 0.9406
Epoch 2/10
60000/60000 [==============================] - 17s 291us/step - loss: 0.0805 - acc: 0.9759
Epoch 3/10
60000/60000 [==============================] - 18s 297us/step - loss: 0.0537 - acc: 0.9837
Epoch 4/10
60000/60000 [==============================] - 18s 298us/step - loss: 0.0371 - acc: 0.9883
Epoch 5/10
60000/60000 [==============================] - 18s 305us/step - loss: 0.0269 - acc: 0.9915
Epoch 6/10
60000/60000 [==============================] - 18s 298us/step - loss: 0.0207 - acc: 0.9933
Epoch 7/10
60000/60000 [==============================] - 18s 301us/step - loss: 0.0172 - acc: 0.9948
Epoch 8/10
60000/60000 [==============================] - 18s 298us/step - loss: 0.0150 - acc: 0.9949
Epoch 9/10
60000/60000 [==============================] - 18s 300us/step - loss: 0.0122 - acc: 0.9965
Epoch 10/10
60000/60000 [==============================] - 16s 275us/step - loss: 